# Generated by Django 5.2.3 on 2025-08-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='current_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('expense_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.current_balance')),
            ],
        ),
    ]
